name: notetaker

services:
  postgres:
    image: postgres:17
    container_name: notetaker_postgres
    environment:
      POSTGRES_DB: notetaker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - notetaker_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notetaker"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  notetaker_postgres_data:
